id_state_name = {
    1: "Aguascalientes",
    2: "Baja California",
    3: "Baja California Sur",
    4: "Campeche",
    5: "Coahuila",
    6: "Colima",
    7: "Chiapas",
    8: "Chihuahua",
    9: "Mexico City",
    10: "Durango",
    11: "Guanajuato",
    12: "Guerrero",
    13: "Hidalgo",
    14: "Jalisco",
    15: "State of Mexico",
    16: "Michoacán",
    17: "Morelos",
    18: "Nayarit",
    19: "Nuevo León",
    20: "Oaxaca",
    21: "Puebla",
    22: "Querétaro",
    23: "Quintana Roo",
    24: "San Luis Potosí",
    25: "Sinaloa",
    26: "Sonora",
    27: "Tabasco",
    28: "Tamaulipas",
    29: "Tlaxcala",
    30: "Veracruz",
    31: "Yucatán",
    32: "Zacatecas"
}

id_state_coordinates = {
    1: (21.8853, -102.2916),
    2: (32.5149, -117.0382),
    3: (24.1426, -110.3128),
    4: (19.8301, -90.5349),
    5: (27.0587, -101.7068),
    6: (19.1138, -104.3385),
    7: (16.7569, -93.1292),
    8: (28.6320, -106.0691),
    9: (19.4326, -99.1332),
    10: (24.0277, -104.6532),
    11: (21.0190, -101.2574),
    12: (17.5519, -99.5058),
    13: (20.0911, -98.7624),
    14: (20.6736, -103.3440),
    15: (19.3574, -99.9650),
    16: (19.7008, -101.1844),
    17: (18.6813, -99.1013),
    18: (21.7514, -104.8455),
    19: (25.5922, -100.9967),
    20: (17.0732, -96.7266),
    21: (19.0413, -98.2062),
    22: (20.5888, -100.3899),
    23: (18.5036, -88.2964),
    24: (22.1565, -100.9855),
    25: (24.8091, -107.3940),
    26: (29.0729, -110.9559),
    27: (17.9895, -92.9475),
    28: (24.2669, -98.8363),
    29: (19.3139, -98.2400),
    30: (19.1738, -96.1342),
    31: (20.7099, -89.0943),
    32: (22.7709, -102.5833)
}

# fsq3jRQ+AaizYAQIJjSe31snrDAUyobhW0O3D+lqZnKzk/Q=

mapeo_categorias = {
    "ABARROTES, CARNICERIAS, PESCADERIAS, MISCELANEAS": {"categoria_foursquare": "Grocery Store", "id_foursquare": "19013"},
    "ACCESORIOS INDUSTRIALES - NO CLASIFICADOS": {"categoria_foursquare": "Hardware Store", "id_foursquare": "19014"},
    "AGENCIAS DE VIAJES OPERADORAS DE VIAJES": {"categoria_foursquare": "Travel Agency", "id_foursquare": "19046"},
    "AGREGADOR": {"categoria_foursquare": "Business Service", "id_foursquare": "19054"},
    "ALIMENTOS - PROVEEDORES Y DISTRIBUIDORES": {"categoria_foursquare": "Food Service", "id_foursquare": "19055"},
    "APARATOS ELECTRONICOS PARA EL HOGAR LINEA BLANCA": {"categoria_foursquare": "Electronics Store", "id_foursquare": "19012"},
    "ASEGURADORAS - VENTAS DE SEGUROS, POLIZAS": {"categoria_foursquare": "Insurance Office", "id_foursquare": "19056"},
    "ASESOR FINANCIERO,CONSEJEROS, MATRIMONIAL,PRESTAMO": {"categoria_foursquare": "Financial Service", "id_foursquare": "19057"},
    "ASESORIAS - COMPRA/VENTA BIENES INMUEBLES": {"categoria_foursquare": "Real Estate Office", "id_foursquare": "19058"},
    "AUTOBUSES FORANEOS": {"categoria_foursquare": "Bus Station", "id_foursquare": "19059"},
    "AUTOFINANCIAMIENTOS - SERVICIOS FINANCIEROS": {"categoria_foursquare": "Financial Service", "id_foursquare": "19057"},
    "AUTOSERVICIOS Y SUPERMERCADOS": {"categoria_foursquare": "Supermarket", "id_foursquare": "19013"},
    "BARES,BEBIDAS ALCOHOLICAS,TABERNAS,DISCOTECAS": {"categoria_foursquare": "Bar", "id_foursquare": "13003"},
    "BIENES DIGITALES APLICACIONES": {"categoria_foursquare": "Mobile Phone Store", "id_foursquare": "19060"},
    "BIENES DIGITALES JUEGOS": {"categoria_foursquare": "Video Game Store", "id_foursquare": "19010"},
    "BOUTIQUES ROPA - NIOS Y BEBES": {"categoria_foursquare": "Kids Store", "id_foursquare": "19061"},
    "BOUTIQUES ROPA - PARA TODA LA FAMILIA": {"categoria_foursquare": "Clothing Store", "id_foursquare": "19062"},
    "CASINOS CASAS DE JUEGO (APUESTAS INCLUYE BILLETES)": {"categoria_foursquare": "Casino", "id_foursquare": "19063"},
    "CINES, TEATROS": {"categoria_foursquare": "Movie Theater", "id_foursquare": "18069"},
    "CLUBES DE MAYORISTA": {"categoria_foursquare": "Warehouse Store", "id_foursquare": "19064"},
    "CLUBS DEPORTIVOS MEMBRESIAS, CLUB CAMPESTRE": {"categoria_foursquare": "Country Club", "id_foursquare": "19065"},
    "COMERCIOS ELECTRONICOS (VTAS POR INTERNET)": {"categoria_foursquare": "Online Store", "id_foursquare": "19066"},
    "COMIDA RAPIDA": {"categoria_foursquare": "Fast Food Restaurant", "id_foursquare": "13145"},
    "COMPAIAS DE - MUDANZAS Y ALMACENAJE": {"categoria_foursquare": "Moving Company", "id_foursquare": "19067"},
    "COMPUTADORAS EQUIPO PERIF DE COMPUTADORAS SOFTWARE": {"categoria_foursquare": "Electronics Store", "id_foursquare": "19012"},
    "CUOTA - PUENTES": {"categoria_foursquare": "Toll Booth", "id_foursquare": "19068"},
    "DEPORTES Y ACCESORIOS": {"categoria_foursquare": "Sporting Goods Store", "id_foursquare": "19069"},
    "DEPOSITOS DE CERVEZAS, VINATERIAS, VINOS Y LICORES": {"categoria_foursquare": "Liquor Store", "id_foursquare": "19070"},
    "DISTRIBUIDORES DE HIELO (FUEGOS ARTIFICIALES)": {"categoria_foursquare": "Specialty Store", "id_foursquare": "19071"},
    "DROGUERIAS, (FARMACIAS)": {"categoria_foursquare": "Pharmacy", "id_foursquare": "17069"},
    "DULCERIAS, PASTELERIAS Y CONFITERIAS, SEMILLAS": {"categoria_foursquare": "Candy Store", "id_foursquare": "19072"},
    "EQUIPO - PLOMERIA Y CALEFACCION": {"categoria_foursquare": "Hardware Store", "id_foursquare": "19014"},
    "EQUIPOS DE TELECOMUNICACION,VTA DE TELEFONOS": {"categoria_foursquare": "Mobile Phone Store", "id_foursquare": "19060"},
    "ESTACIONAMIENTOS/PENSIONES": {"categoria_foursquare": "Parking", "id_foursquare": "19073"},
    "ESTACIONES DE SERVICIO, GASOLINERIAS TODO TRANSPOR": {"categoria_foursquare": "Gas Station", "id_foursquare": "19074"},
    "FERRETERIAS, ACCESORIOS Y EQUIPO": {"categoria_foursquare": "Hardware Store", "id_foursquare": "19014"},
    "FOTOGRAFIA, ARTE Y ANUNCIOS - COMERCIALES": {"categoria_foursquare": "Photography Studio", "id_foursquare": "19075"},
    "GIROS BANCARIOS/POSTALES": {"categoria_foursquare": "Bank", "id_foursquare": "19076"},
    "JARDINES BOTANICOS(ZOO, SERVICIOS DE ENTREMIENTO)": {"categoria_foursquare": "Zoo", "id_foursquare": "16025"},
    "LIBRERIAS": {"categoria_foursquare": "Bookstore", "id_foursquare": "19005"},
    "LIMOSINAS, (TAXIS)": {"categoria_foursquare": "Taxi Service", "id_foursquare": "19077"},
    "MEDICINAS, MEDICINAS DE PATENTE, FARMACOS DIVERSOS": {"categoria_foursquare": "Pharmacy", "id_foursquare": "17069"},
    "MEDIOS DE COMUNICACION DIGITAL LIBROS PELICULAS MU": {"categoria_foursquare": "Media Store", "id_foursquare": "19078"},
    "MERCADEO DIRECTO - COMERCIANTES DE TELEMERCADEO": {"categoria_foursquare": "Marketing Agency", "id_foursquare": "19079"},
    "MERCADEO DIRECTO - NO CLASIFICADO": {"categoria_foursquare": "Marketing Agency", "id_foursquare": "19079"},
    "MERCADO DIRECTO - VENTAS POR CATALOGO": {"categoria_foursquare": "Catalog Store", "id_foursquare": "19080"},
    "OPTICAS, LENTES Y ANTEOJOS": {"categoria_foursquare": "Optical Shop", "id_foursquare": "19081"},
    "ORDENES DE PAGO, INSTITUCIONES NO FINANCIERAS": {"categoria_foursquare": "Financial Service", "id_foursquare": "19057"},
    "PAGO DE IMPUESTOS": {"categoria_foursquare": "Government Office", "id_foursquare": "19082"},
    "PAGO DE SERVICIO POR TELEVISION CABLE/POR EVENTO": {"categoria_foursquare": "Telecommunications Service Provider", "id_foursquare": "19083"},
    "PANADERIAS": {"categoria_foursquare": "Bakery", "id_foursquare": "13070"},
    "PRODUCCION Y DISTRIBUCION DE PELICULAS Y VIDEOS": {"categoria_foursquare": "Movie Theater", "id_foursquare": "18069"},
    "RENTA DE VIDEOS  (VIDEOS)": {"categoria_foursquare": "Video Store", "id_foursquare": "19084"},
    "RESTAURANTES": {"categoria_foursquare": "Restaurant", "id_foursquare": "13065"},
    "ROPA CASUAL DAMAS LENCERIA": {"categoria_foursquare": "Women's Store", "id_foursquare": "19085"},
    "ROPA Y ACCESORIOS - MISCELANEOS": {"categoria_foursquare": "Clothing Store", "id_foursquare": "19062"},
    "SALONES DE BELLEZA, (PELUQUERIAS), (ESTETICAS)": {"categoria_foursquare": "Salon / Barbershop", "id_foursquare": "19086"},
    "SERV GUBERNAM, AGUA, ELECTRICIDAD,PREDIAL,TENENCIA": {"categoria_foursquare": "Government Office", "id_foursquare": "19082"},
    "SERV NO CLASIFICADOS HOTELES, MOTELES,CTROS TURIST": {"categoria_foursquare": "Hotel", "id_foursquare": "19087"},
    "SERV PROC DATOS - DISENO Y PROGRAM DE SISTEMAS": {"categoria_foursquare": "IT Services", "id_foursquare": "19088"},
    "SERVICIO - LAVADO DE AUTOS": {"categoria_foursquare": "Car Wash", "id_foursquare": "19089"},
    "SERVICIOS DE CONSULTA/ENCUESTAS DE INFORMACION": {"categoria_foursquare": "Consulting Service", "id_foursquare": "19090"},
    "SERVICIOS DE TELECOMUNICACION, LLAMADAS LOC Y LARG": {"categoria_foursquare": "Telecommunications Service Provider", "id_foursquare": "19083"},
    "TIENDAS DE CONVENIENCIA, MINISUPER": {"categoria_foursquare": "Convenience Store", "id_foursquare": "4bf58dd8d48988d118951735"}
}
 
